version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: jonathanssantiagodev/eldorado-challenge-api
    env_file:
      - .env
    ports:
      - '80:3000'
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eldorado_challenge
      MYSQL_USER: eldorado_user
      MYSQL_PASSWORD: eldorado_password
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
