version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: device_management
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/device_management
    ports:
      - '3000:3000'
    volumes:
      - ./:/app

volumes:
  db_data:
