name: CI/CD - Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            jonathanssantiagodev/eldorado-challenge-api:latest
            jonathanssantiagodev/eldorado-challenge-api:${{ github.sha }}
          build-args: |
            NODE_ENV=production
            PORT=3000
            DATABASE_URL=mysql://aaa:bbb@eldorado-db.ccsda.us-east-1.rds.amazonaws.com:3306/ccc
